#!/bin/bash -e

# Colors for prettier output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Print an info message
info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

# Print a warning message
warning() {
  echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Print an error message
error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

# Configuration with defaults
CONFIG_FILE="${1:-/tmp/k8-highlander/config/config.yaml}"
REMAIN_FOLLOWER="${2:-false}"

# Check if config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    error "Configuration file not found: $CONFIG_FILE"
    error "Please run setup_config.sh first to create the configuration"
    exit 1
fi

# Source environment variables if they exist
if [ -f "/tmp/k8-highlander/env.sh" ]; then
    info "Loading environment variables from /tmp/k8-highlander/env.sh"
    source /tmp/k8-highlander/env.sh
fi

# Display configuration
info "Starting controller with configuration:"
info "Config file: $CONFIG_FILE"
info "Controller ID: ${HIGHLANDER_ID:-<auto-generated>}"
info "Remain follower: $REMAIN_FOLLOWER"

if [ "$REMAIN_FOLLOWER" == "true" ]; then
    export HIGHLANDER_REMAINS_FOLLOWER=true
    info "This instance will remain a follower and won't attempt to become a leader"
fi

# Run the controller
info "Starting K8-Highlander controller..."
go run cmd/main.go --config "$CONFIG_FILE"
